# Generated by Django 4.2.8 on 2023-12-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('MP', 'Mass Production'), ('T', 'Trial'), ('I', 'Inactive')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
