# Generated by Django 4.2.8 on 2023-12-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Mass Production', 'MP'), ('Trial', 'T'), ('Inactive', 'I')], max_length=20),
        ),
    ]
