# Generated by Django 4.2.8 on 2023-12-12 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_customer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('legal_name', models.CharField(max_length=100)),
                ('volume', models.IntegerField()),
                ('type', models.CharField(choices=[('Coffee', 'Coffee'), ('Tea', 'Tea'), ('Flavored Drink', 'Flavored Drink'), ('Coconut Water', 'Coconut Water'), ('Isotonic', 'Isotonic'), ('Soya', 'Soya')], default='Tea', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('domestic_distribution', models.BooleanField(default=True)),
                ('export_distribution', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
            ],
        ),
    ]
