# Generated by Django 4.2.8 on 2023-12-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product_remark_alter_product_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Coffee Drink', 'Coffee Drink'), ('Tea Drink', 'Tea Drink'), ('Flavored Drink', 'Flavored Drink'), ('Botanical Drink', 'Botanical Drink'), ('Isotonic Drink', 'Isotonic Drink'), ('Soya Drink', 'Soya Drink')], default='Tea', max_length=50),
        ),
    ]
